### ISSUE TITLE
practica conexion

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-kem#1]
[conexion a la base de datos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-kem/files/15484722/conexion.a.la.base.de.datos.pdf)

**Comment by josealfredo79** [comment]
Bien hehcho y revisado...Calificacion 20
